RentalKendaraan_20180140050/Models/Pengembalian.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RentalKendaraan_20180140050.Models
{
    public partial class Pengembalian
    {
        [Required(ErrorMessage = "Id Pengembalian tidak boleh kosong")]
        public int IdPengembalian { get; set; }

        [Required(ErrorMessage = "Tanggal tidak boleh kosong")]
        public DateTime? TglPengembalian { get; set; }

        [Required(ErrorMessage = "ID Peminjaman tidak boleh kosong")]
        public int? IdPeminjaman { get; set; }

        [Required(ErrorMessage = "ID Kondisi tidak boleh kosong")]
        public int? IdKondisi { get; set; }

        [Required(ErrorMessage = "Denda tidak boleh kosong")]
        public int? Denda { get; set; }

        public KondisiKendaraan IdKondisiNavigation { get; set; }
        public Peminjaman IdPeminjamanNavigation { get; set; }
    }
}

RentalKendaraan_20180140050/Controllers/PengembaliansController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RentalKendaraan_20180140050.Models;

namespace RentalKendaraan_20180140050.Controllers
{
    public class PengembaliansController : Controller
    {
        private readonly RentalkendaraanContext _context;

        public PengembaliansController(RentalkendaraanContext context)
        {
            _context = context;
        }

        // GET: Pengembalians
        public async Task<IActionResult> Index(string ktsd, string searchString, string sortOrder, string currentFilter, int? pageNumber)
        {
           // buat list untuk menyimpan ketersediaan
            var ktsdList = new List<string>();

            //query mengambil data
            var ktsdQuery = from d in _context.Pengembalian orderby d.TglPengembalian select d.TglPengembalian.ToString();

            ktsdList.AddRange(ktsdQuery.Distinct());

            //untuk menampilkan di view
            ViewBag.ktsd = new SelectList(ktsdList);

            //panggil db context
            var menu = from m in _context.Pengembalian select m;

            //untuk memilih dropdownlist ketersediaan
            if (!string.IsNullOrEmpty(ktsd))
            {
                menu = menu.Where(x => x.TglPengembalian.ToString() == ktsd);
            }

            //untuk search data
            if (!string.IsNullOrEmpty(searchString))
            {
                menu = menu.Where(s => s.Denda.ToString().Contains(searchString));
            }

            //membuat pagedlist
            ViewData["CurrentShort"] = sortOrder;
            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewData["CurrentFilter"] = searchString;

            //definisi jumlah data pada halaman
            int pageSize = 5;

            //untuk sorting
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";
            switch (sortOrder)
            {
                case "name_desc":
                    menu = menu.OrderByDescending(s => s.IdKondisiNavigation.NamaKondisi);
                    break;
                case "Date":
                    menu = menu.OrderBy(s => s.TglPengembalian);
                    break;
                case "date_desc":
                    menu = menu.OrderByDescending(s => s.TglPengembalian);
                    break;
                default: //name ascending
                    menu = menu.OrderBy(s => s.IdKondisiNavigation.NamaKondisi);
                    break;
            }

            return View(await PaginatedList<Pengembalian>.CreateAsync(menu.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        // GET: Pengembalians/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pengembalian = await _context.Pengembalian
                .Include(p => p.IdKondisiNavigation)
                .Include(p => p.IdPeminjamanNavigation)
                .FirstOrDefaultAsync(m => m.IdPengembalian == id);
            if (pengembalian == null)
            {
                return NotFound();
            }

            return View(pengembalian);
        }

        // GET: Pengembalians/Create
        public IActionResult Create()
        {
            ViewData["IdKondisi"] = new SelectList(_context.KondisiKendaraan, "IdKondisi", "IdKondisi");
            ViewData["IdPeminjaman"] = new SelectList(_context.Peminjaman, "IdPeminjaman", "IdPeminjaman");
            return View();
        }

        // POST: Pengembalians/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdPengembalian,TglPengembalian,IdPeminjaman,IdKondisi,Denda")] Pengembalian pengembalian)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pengembalian);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdKondisi"] = new SelectList(_context.KondisiKendaraan, "IdKondisi", "IdKondisi", pengembalian.IdKondisi);
            ViewData["IdPeminjaman"] = new SelectList(_context.Peminjaman, "IdPeminjaman", "IdPeminjaman", pengembalian.IdPeminjaman);
            return View(pengembalian);
        }

        // GET: Pengembalians/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pengembalian = await _context.Pengembalian.FindAsync(id);
            if (pengembalian == null)
            {
                return NotFound();
            }
            ViewData["IdKondisi"] = new SelectList(_context.KondisiKendaraan, "IdKondisi", "IdKondisi", pengembalian.IdKondisi);
            ViewData["IdPeminjaman"] = new SelectList(_context.Peminjaman, "IdPeminjaman", "IdPeminjaman", pengembalian.IdPeminjaman);
            return View(pengembalian);
        }

        // POST: Pengembalians/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdPengembalian,TglPengembalian,IdPeminjaman,IdKondisi,Denda")] Pengembalian pengembalian)
        {
            if (id != pengembalian.IdPengembalian)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pengembalian);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PengembalianExists(pengembalian.IdPengembalian))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdKondisi"] = new SelectList(_context.KondisiKendaraan, "IdKondisi", "IdKondisi", pengembalian.IdKondisi);
            ViewData["IdPeminjaman"] = new SelectList(_context.Peminjaman, "IdPeminjaman", "IdPeminjaman", pengembalian.IdPeminjaman);
            return View(pengembalian);
        }

        // GET: Pengembalians/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pengembalian = await _context.Pengembalian
                .Include(p => p.IdKondisiNavigation)
                .Include(p => p.IdPeminjamanNavigation)
                .FirstOrDefaultAsync(m => m.IdPengembalian == id);
            if (pengembalian == null)
            {
                return NotFound();
            }

            return View(pengembalian);
        }

        // POST: Pengembalians/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pengembalian = await _context.Pengembalian.FindAsync(id);
            _context.Pengembalian.Remove(pengembalian);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PengembalianExists(int id)
        {
            return _context.Pengembalian.Any(e => e.IdPengembalian == id);
        }
    }
}

RentalKendaraan_20180140050/Views/Pengembalians/Create.cshtml
@model RentalKendaraan_20180140050.Models.Pengembalian

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Pengembalian</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdPengembalian" class="control-label"></label>
                <input asp-for="IdPengembalian" class="form-control" />
                <span asp-validation-for="IdPengembalian" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TglPengembalian" class="control-label"></label>
                <input asp-for="TglPengembalian" class="form-control" />
                <span asp-validation-for="TglPengembalian" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdPeminjaman" class="control-label"></label>
                <select asp-for="IdPeminjaman" class ="form-control" asp-items="ViewBag.IdPeminjaman"></select>
            </div>
            <div class="form-group">
                <label asp-for="IdKondisi" class="control-label"></label>
                <select asp-for="IdKondisi" class ="form-control" asp-items="ViewBag.IdKondisi"></select>
            </div>
            <div class="form-group">
                <label asp-for="Denda" class="control-label"></label>
                <input asp-for="Denda" class="form-control" />
                <span asp-validation-for="Denda" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RentalKendaraan_20180140050/Views/Pengembalians/Delete.cshtml
@model RentalKendaraan_20180140050.Models.Pengembalian

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pengembalian</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TglPengembalian)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TglPengembalian)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Denda)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Denda)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdKondisiNavigation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdKondisiNavigation.IdKondisi)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdPeminjamanNavigation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdPeminjamanNavigation.IdPeminjaman)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdPengembalian" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

RentalKendaraan_20180140050/Views/Pengembalians/Details.cshtml
@model RentalKendaraan_20180140050.Models.Pengembalian

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Pengembalian</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TglPengembalian)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TglPengembalian)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Denda)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Denda)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdKondisiNavigation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdKondisiNavigation.IdKondisi)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdPeminjamanNavigation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdPeminjamanNavigation.IdPeminjaman)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.IdPengembalian">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

RentalKendaraan_20180140050/Views/Pengembalians/Edit.cshtml
@model RentalKendaraan_20180140050.Models.Pengembalian

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Pengembalian</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdPengembalian" />
            <div class="form-group">
                <label asp-for="TglPengembalian" class="control-label"></label>
                <input asp-for="TglPengembalian" class="form-control" />
                <span asp-validation-for="TglPengembalian" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdPeminjaman" class="control-label"></label>
                <select asp-for="IdPeminjaman" class="form-control" asp-items="ViewBag.IdPeminjaman"></select>
                <span asp-validation-for="IdPeminjaman" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdKondisi" class="control-label"></label>
                <select asp-for="IdKondisi" class="form-control" asp-items="ViewBag.IdKondisi"></select>
                <span asp-validation-for="IdKondisi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Denda" class="control-label"></label>
                <input asp-for="Denda" class="form-control" />
                <span asp-validation-for="Denda" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RentalKendaraan_20180140050/Views/Pengembalians/Index.cshtml
@model IEnumerable<RentalKendaraan_20180140050.Models.Pengembalian>

@{
    ViewData["Title"] = "Index";
}

<h2>Tambah Data</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>

@using (Html.BeginForm("Index", "Pengembalians", FormMethod.Get))
{
    <p>
        Tanggal Pengembalian: @Html.DropDownList("ktsd", "Pilih Tanggal")
        Cari Data : @Html.TextBox("searchString")
        <input type="submit" value="Filter" />
    </p>
}

<table class="table">
    <thead>
        <tr>
            <th>
                @*@Html.DisplayName("Tgl Pengembalian")*@
                <a asp-action="Index" 
                    asp-route-sortOrder="@ViewData["DateSortParm"]" 
                    asp-route-currentFilter="@ViewData["CurrentFilter"]">Tanggal Pengembalian</a>
            </th>
            <th>
                @Html.DisplayName("Denda")
            </th>
            <th>
                @*@Html.DisplayName("Nama Kondisi")*@
                <a asp-action="Index" 
                    asp-route-sortOrder="@ViewData["NameSortParm"]" 
                    asp-route-currentFilter="@ViewData["CurrentFilter"]">Kondisi</a>
            </th>
            <th>
                @Html.DisplayName("Tgl Peminjaman")
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
         {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TglPengembalian)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Denda)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdKondisiNavigation.IdKondisi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdPeminjamanNavigation.IdPeminjaman)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.IdPengembalian">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.IdPengembalian">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.IdPengembalian">Delete</a>
                </td>
            </tr>
         }
    </tbody>
</table>