RentalKendaraan_20180140050/Controllers/PeminjamenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RentalKendaraan_20180140050.Models;
using Microsoft.AspNetCore.Authorization;

namespace RentalKendaraan_20180140050.Controllers
{
    public class PeminjamenController : Controller
    {
        private readonly RentalkendaraanContext _context;

        public PeminjamenController(RentalkendaraanContext context)
        {
            _context = context;
        }

        [Authorize(Policy ="readonlypolicy")]
        // GET: Peminjamen
        public async Task<IActionResult> Index(string ktsd, string searchString, string sortOrder, string currentFilter, int? pageNumber)
        {
            // buat list untuk menyimpan ketersediaan
            var ktsdList = new List<string>();

            //query mengambil data
            var ktsdQuery = from d in _context.Peminjaman orderby d.TglPeminjaman select d.TglPeminjaman.ToString();
            ktsdList.AddRange(ktsdQuery.Distinct());

            //untuk menampilkan di view
            ViewBag.ktsd = new SelectList(ktsdList);

            //pangil db context
            var menu = from m in _context.Peminjaman.Include(p => p.IdCostumerNavigation).Include(p => p.IdJaminanNavigation).Include(p => p.IdKendaraanNavigation) select m;

            //untuk memilih dropdownlist ketersediaan
            if (!string.IsNullOrEmpty(ktsd))
            {
                menu = menu.Where(x => x.TglPeminjaman.ToString() == ktsd);
            }

            //untuk search data
            if (!string.IsNullOrEmpty(searchString))
            {
                menu = menu.Where(s => s.TglPeminjaman.ToString().Contains(searchString));
            }
            //membuat pagedlist

            ViewData["CurrentSort"] = sortOrder;

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewData["CurrentFilter"] = searchString;

            //definisi jumlah data pada halaman
            int pageSize = 5;

            //untuk sorting
            ViewData["NamaSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_decs" : "";
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";
            switch (sortOrder)
            {
                case "name_desc":
                    menu = menu.OrderByDescending(s => s.IdCostumerNavigation.NamaCustomer);
                    break;
                case "Date":
                    menu = menu.OrderBy(s => s.TglPeminjaman);
                    break;
                case "date_desc":
                    menu = menu.OrderByDescending(s => s.TglPeminjaman);
                    break;
                default: //name ascending
                    menu = menu.OrderBy(s => s.IdCostumerNavigation.NamaCustomer);
                    break;
            }

            return View(await PaginatedList<Peminjaman>.CreateAsync(menu.AsNoTracking(),pageNumber ?? 1, pageSize));

        }

        // GET: Peminjamen/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var peminjaman = await _context.Peminjaman
                .Include(p => p.IdCostumerNavigation)
                .Include(p => p.IdJaminanNavigation)
                .Include(p => p.IdKendaraanNavigation)
                .FirstOrDefaultAsync(m => m.IdPeminjaman == id);
            if (peminjaman == null)
            {
                return NotFound();
            }

            return View(peminjaman);
        }

        [Authorize(Policy ="writepolicy")]
        // GET: Peminjamen/Create
        public IActionResult Create()
        {
            ViewData["IdCostumer"] = new SelectList(_context.Customer, "IdCustomer", "IdCustomer");
            ViewData["IdJaminan"] = new SelectList(_context.Jaminan, "IdJaminan", "IdJaminan");
            ViewData["IdKendaraan"] = new SelectList(_context.Kendaraan, "IdKendaraan", "IdKendaraan");
            return View();
        }

        // POST: Peminjamen/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdPeminjaman,TglPeminjaman,IdKendaraan,IdCostumer,IdJaminan,Biaya")] Peminjaman peminjaman)
        {
            if (ModelState.IsValid)
            {
                _context.Add(peminjaman);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdCostumer"] = new SelectList(_context.Customer, "IdCustomer", "IdCustomer", peminjaman.IdCostumer);
            ViewData["IdJaminan"] = new SelectList(_context.Jaminan, "IdJaminan", "IdJaminan", peminjaman.IdJaminan);
            ViewData["IdKendaraan"] = new SelectList(_context.Kendaraan, "IdKendaraan", "IdKendaraan", peminjaman.IdKendaraan);
            return View(peminjaman);
        }

        [Authorize(Policy ="editpolicy")]
        // GET: Peminjamen/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var peminjaman = await _context.Peminjaman.FindAsync(id);
            if (peminjaman == null)
            {
                return NotFound();
            }
            ViewData["IdCostumer"] = new SelectList(_context.Customer, "IdCustomer", "IdCustomer", peminjaman.IdCostumer);
            ViewData["IdJaminan"] = new SelectList(_context.Jaminan, "IdJaminan", "IdJaminan", peminjaman.IdJaminan);
            ViewData["IdKendaraan"] = new SelectList(_context.Kendaraan, "IdKendaraan", "IdKendaraan", peminjaman.IdKendaraan);
            return View(peminjaman);
        }

        // POST: Peminjamen/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdPeminjaman,TglPeminjaman,IdKendaraan,IdCostumer,IdJaminan,Biaya")] Peminjaman peminjaman)
        {
            if (id != peminjaman.IdPeminjaman)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(peminjaman);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PeminjamanExists(peminjaman.IdPeminjaman))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdCostumer"] = new SelectList(_context.Customer, "IdCustomer", "IdCustomer", peminjaman.IdCostumer);
            ViewData["IdJaminan"] = new SelectList(_context.Jaminan, "IdJaminan", "IdJaminan", peminjaman.IdJaminan);
            ViewData["IdKendaraan"] = new SelectList(_context.Kendaraan, "IdKendaraan", "IdKendaraan", peminjaman.IdKendaraan);
            return View(peminjaman);
        }

        [Authorize(Policy ="deletepolicy")]
        // GET: Peminjamen/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var peminjaman = await _context.Peminjaman
                .Include(p => p.IdCostumerNavigation)
                .Include(p => p.IdJaminanNavigation)
                .Include(p => p.IdKendaraanNavigation)
                .FirstOrDefaultAsync(m => m.IdPeminjaman == id);
            if (peminjaman == null)
            {
                return NotFound();
            }

            return View(peminjaman);
        }

        // POST: Peminjamen/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var peminjaman = await _context.Peminjaman.FindAsync(id);
            _context.Peminjaman.Remove(peminjaman);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PeminjamanExists(int id)
        {
            return _context.Peminjaman.Any(e => e.IdPeminjaman == id);
        }
    }
}

RentalKendaraan_20180140050/Views/Peminjamen/Create.cshtml
@model RentalKendaraan_20180140050.Models.Peminjaman

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Peminjaman</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdPeminjaman" class="control-label"></label>
                <input asp-for="IdPeminjaman" class="form-control" />
                <span asp-validation-for="IdPeminjaman" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TglPeminjaman" class="control-label"></label>
                <input asp-for="TglPeminjaman" class="form-control" />
                <span asp-validation-for="TglPeminjaman" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdKendaraan" class="control-label"></label>
                <select asp-for="IdKendaraan" class ="form-control" asp-items="ViewBag.IdKendaraan"></select>
            </div>
            <div class="form-group">
                <label asp-for="IdCostumer" class="control-label"></label>
                <select asp-for="IdCostumer" class ="form-control" asp-items="ViewBag.IdCostumer"></select>
            </div>
            <div class="form-group">
                <label asp-for="IdJaminan" class="control-label"></label>
                <select asp-for="IdJaminan" class ="form-control" asp-items="ViewBag.IdJaminan"></select>
            </div>
            <div class="form-group">
                <label asp-for="Biaya" class="control-label"></label>
                <input asp-for="Biaya" class="form-control" />
                <span asp-validation-for="Biaya" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RentalKendaraan_20180140050/Views/Peminjamen/Delete.cshtml
@model RentalKendaraan_20180140050.Models.Peminjaman

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Peminjaman</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TglPeminjaman)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TglPeminjaman)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Biaya)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Biaya)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdCostumerNavigation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdCostumerNavigation.IdCustomer)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdJaminanNavigation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdJaminanNavigation.IdJaminan)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdKendaraanNavigation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdKendaraanNavigation.IdKendaraan)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdPeminjaman" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

RentalKendaraan_20180140050/Views/Peminjamen/Details.cshtml
@model RentalKendaraan_20180140050.Models.Peminjaman

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Peminjaman</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TglPeminjaman)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TglPeminjaman)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Biaya)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Biaya)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdCostumerNavigation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdCostumerNavigation.IdCustomer)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdJaminanNavigation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdJaminanNavigation.IdJaminan)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdKendaraanNavigation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdKendaraanNavigation.IdKendaraan)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.IdPeminjaman">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

RentalKendaraan_20180140050/Views/Peminjamen/Edit.cshtml
@model RentalKendaraan_20180140050.Models.Peminjaman

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Peminjaman</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdPeminjaman" />
            <div class="form-group">
                <label asp-for="TglPeminjaman" class="control-label"></label>
                <input asp-for="TglPeminjaman" class="form-control" />
                <span asp-validation-for="TglPeminjaman" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdKendaraan" class="control-label"></label>
                <select asp-for="IdKendaraan" class="form-control" asp-items="ViewBag.IdKendaraan"></select>
                <span asp-validation-for="IdKendaraan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdCostumer" class="control-label"></label>
                <select asp-for="IdCostumer" class="form-control" asp-items="ViewBag.IdCostumer"></select>
                <span asp-validation-for="IdCostumer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdJaminan" class="control-label"></label>
                <select asp-for="IdJaminan" class="form-control" asp-items="ViewBag.IdJaminan"></select>
                <span asp-validation-for="IdJaminan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Biaya" class="control-label"></label>
                <input asp-for="Biaya" class="form-control" />
                <span asp-validation-for="Biaya" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RentalKendaraan_20180140050/Views/Peminjamen/Index.cshtml
@model PaginatedList<RentalKendaraan_20180140050.Models.Peminjaman>

@{
    ViewData["Title"] = "Index";
}

<h2>Tambah Data Peminjaman</h2>

<p>
    <a asp-action="Create">Tambah Data Baru</a>
</p>

@using (Html.BeginForm("Index", "Peminjamen", FormMethod.Get))
{
    <p>
        Tanggal Peminjaman: @Html.DropDownList("ktsd", "Pilih Tanggal")
        Cari Data : @Html.TextBox("searchString")
        <input type="submit" value="Filter" />
    </p>
}

<table class="table">
    <thead>
        <tr>
            <th>
                @*Html.DisplayName("Tanggal Peminjaman")*@
                <a asp-action="Index" 
                    asp-route-sortOrder="@ViewData["DateSortParm"]" 
                    asp-route-currentFilter="@ViewData["CurrentFilter"]">Tanggal Peminjaman</a>

            </th>
            <th>
                @*Html.DisplayName("Id Customer")*@
                <a asp-action="Index" 
                    asp-route-sortOrder="@ViewData["NamaSortParm"]" 
                    asp-route-currentFilter="@ViewData["CurrentFilter"]">Nama Customer</a>
            </th>
            <th>
                @Html.DisplayName("Biaya")
            </th>

            <th>
                @Html.DisplayName("Id Jaminan")
            </th>
            <th>
                @Html.DisplayName("Id Kendaraan")
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TglPeminjaman)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Biaya)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdCostumerNavigation.IdCustomer)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdJaminanNavigation.IdJaminan)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdKendaraanNavigation.IdKendaraan)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.IdPeminjaman">
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pen-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M13.498.795l.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001z" />
                        </svg>
                    </a> |
                    <a asp-action="Details" asp-route-id="@item.IdPeminjaman">
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-card-list" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M14.5 3h-13a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h13a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z" />
                            <path fill-rule="evenodd" d="M5 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 5 8zm0-2.5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5zm0 5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5z" />
                            <circle cx="3.5" cy="5.5" r=".5" />
                            <circle cx="3.5" cy="8" r=".5" />
                            <circle cx="3.5" cy="10.5" r=".5" />
                        </svg>
                    </a> |
                    <a asp-action="Delete" asp-route-id="@item.IdPeminjaman">
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5a.5.5 0 0 0-1 0v7a.5.5 0 0 0 1 0v-7z" />
                        </svg>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}
<a asp-action="Index"
    asp-route-sortOrder="@ViewData["CurrentSort"]"
    asp-route-pageNumber ="@(Model.PageIndex +1 )"
    asp-route-currentFilter="@ViewData["CurrentFilter"]"
    class="btn btn-default @prevDisabled">
    Previous
</a>
<a asp-action="Index"
   asp-route-sortOrder="@ViewData[" CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex + 1 )"
   asp-route-currentFilter="@ViewData[" CurrentFilter"]"
   class= " btn btn-default @prevDisabled">
   Next
</a>